services:
  frontend:
    image: node:22-alpine
    container_name: mynewshub-frontend
    working_dir: /app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:8080/api
      - API_URL=http://mynewshub-webserver:8080/api
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=e30So6R7VFFaU9Gojhd6zDWpSWtYPO/zDxevika39uM=
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    command: sh -c "npm install && npm run dev"
    restart: unless-stopped
    stdin_open: true
    tty: true
    networks:
      - mynewshub-network
      - backend_mynewshub-network

volumes:
  node_modules:

networks:
  mynewshub-network:
    driver: bridge
  backend_mynewshub-network:
    external: true
